# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 0.1
mod_id = phoenix
mod_group = dev.tnt.phoenix
mod_name = Phoenix
mod_authors = Toma, Tomano
# TODO
mod_description = tbd
mod_license = All rights reserved

# Minecraft properties
java_version = 25
minecraft_version = 26.2
minecraft_version_range = [26.2,)

# Environment
vanilla_gradle_version = 0.3.2
mixin_loader = 0.7-SNAPSHOT
mixin_version = 0.8.6
mixin_min_version = 0.8
fabric_loader_version = 0.19.3
fabric_loader_version_range = >=0.19.0
fabric_version = 0.152.2+26.2
fabric_version_range = *
fabric_loom = 1.17-SNAPSHOT
fabric_mc_version_range = 26.2
neoforge_version = 26.2.0.3-beta
neoforge_version_range = [26.2,)
neogradle_version = 7.1.38

# Publish
cursegradle_plugin_version = 1.1.25
modrinth_plugin_version = 2.+
compatible_mc_versions = 26.2
curseforge_project_id = tbd
modrinth_project_id = tbd
debug_publish = true