plugins {
    id 'org.spongepowered.gradle.vanilla' version "${vanilla_gradle_version}"
}

minecraft {
    version("${minecraft_version}")

    def accessWidenerFile = file("src/main/resources/${mod_id}.accesswidener")
    if (accessWidenerFile.exists()) {
        accessWideners(accessWidenerFile)
    }

    runs {
    }
}

jar {
    archiveFileName = "${mod_id}-common-${project.version}.jar"
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: "${mixin_version}"
}
