name: Release
on:
  push:
    tags:
      - 'version/*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '25'

      - run: chmod +x ./gradlew

      - run: ./gradlew releaseMod -PCURSEFORGE_TOKEN=${{ secrets.CF_TOKEN }} -PMODRINTH_TOKEN=${{ secrets.MODRINTH_TOKEN }} --no-configuration-cache