name: Release
on:
  push:
    tags:
      - 'version/*'

env:
  JAVA_VENDOR: 'microsoft'
  JAVA_VERSION: '25'
  GAME_ENV: 'Client,Server'
  GAME_VERSION: '26.2'
  GAME_DEPENDENCIES: 'configuration'
  CURSEFORGE_PROJECT: '1630968'
  MODRINTH_PROJECT: 'SirewTwV'
  DEBUG: 'false'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        loader: ${{ fromJSON(vars.LOADERS) }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: ${{ env.JAVA_VENDOR }}
          java-version: ${{ env.JAVA_VERSION }}
      - uses: gradle/actions/setup-gradle@v6
      - run: chmod +x ./gradlew
      - run: ./gradlew :${{ matrix.loader.id }}:assemble --no-configuration-cache
      - uses: actions/upload-artifact@v7
        with:
          name: artifact-${{ matrix.loader.id }}
          path: ${{ matrix.loader.id }}/build/libs/*-${{ matrix.loader.id }}-*.jar
          retention-days: 1
          if-no-files-found: error

  prepare-changelog:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.content }}
    steps:
      - uses: actions/checkout@v7
      - uses: Toma1O6/file-read-action@v1
        id: changelog
        with:
          file: 'CHANGELOG.md'
          max-chars: '4096'

  publish-curseforge:
    runs-on: ubuntu-latest
    needs:
      - build
      - prepare-changelog
    strategy:
      fail-fast: false
      matrix:
        loader: ${{ fromJSON(vars.LOADERS) }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifact-${{ matrix.loader.id }}
          path: 'artifacts'
      - uses: T-T-Team/curseforge-publish-action@v1
        with:
          artifact-directory: 'artifacts'
          token: ${{ secrets.CF_TOKEN }}
          project-id: ${{ env.CURSEFORGE_PROJECT }}
          game-version: ${{ env.GAME_VERSION }}
          mod-loader: ${{ matrix.loader.name }}
          game-environment: ${{ env.GAME_ENV }}
          java-version: Java ${{ env.JAVA_VERSION }}
          changelog-content: ${{ needs.prepare-changelog.outputs.changelog }}
          required-dependencies: ${{ env.GAME_DEPENDENCIES }}
          debug-mode: ${{ env.DEBUG }}

  publish-modrinth:
    runs-on: ubuntu-latest
    needs:
      - build
      - prepare-changelog
    strategy:
      fail-fast: false
      matrix:
        loader: ${{ fromJSON(vars.LOADERS) }}
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: artifact-${{ matrix.loader.id }}
          path: 'artifacts'
      - uses: T-T-Team/modrinth-publish-action@v1
        with:
          artifact-directory: 'artifacts'
          token: ${{ secrets.MODRINTH_TOKEN }}
          project-id: ${{ env.MODRINTH_PROJECT }}
          game-version: ${{ env.GAME_VERSION }}
          mod-loader: ${{ matrix.loader.name }}
          changelog-content: ${{ needs.prepare-changelog.outputs.changelog }}
          required-dependencies: ${{ env.GAME_DEPENDENCIES }}
          debug-mode: ${{ env.DEBUG }}